### GENERAL SETTINGS ###

# Site settings
title: LightXlab
theme: solid
description: "LightXlab is an optics simulation program simulating combinations of plane mirror, spherical mirror and parabolics mirror developed by Satvik Ramaprasad. "
analytics: UA-61876800-1 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/LightXlab" #important: start with /
url: "http://lightxlab.satvikramaprasad.space"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Some Ave, 987,
    - 23890, New York,
    - United States.
email: hello@solidtheme.com
tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "LightXlab is an optics simulation program simulating combinations of plane mirror, spherical mirror and parabolics mirror developed by Satvik Ramaprasad."
